stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build typescript-express-server:
  stage: build
  image: node:10.16.0-alpine
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/

test typescript-express-server:
  stage: test
  image: node:10.16.0-alpine
  services:
    - name: postgres
      alias: postgres
  variables:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: example
  script:
    - npm run ci
